Revert "Add jobs and reservations privacy settings"
This reverts commit 27a47fda11835656539479071829901d58e3f27c since it
has several issues. Notably, it does not compile on python 2.6:

$ python -m py_compile rest/slurmrestapi.py
SyntaxError: ('invalid syntax', ('rest/slurmrestapi.py', 241, 24, ' \
  return {k: v for k, v in reservations.iteritems()\n'))

The feature is reviewed in PR #149.