chore(ci): fix pyasn1 dep error on python 3.6
This error now raises on Python 3.6:

  error: pyasn1 0.5.1 is installed but pyasn1<0.7.0,>=0.6.1 is required
  by {'pyasn1-modules'}

The pyasn1 dependency is due to python-ldap. Try to fix it by installing
an older version of python-ldap, similarly to el8.