User extended interpolation in configparser
In restapi.conf, roles can be defined with whitelisted IP addresses
that skip other form of authentication. The syntax is %ip but percent
sign is now also used by recent version of default interpolation
handler of configparser. When IP addresses are declared, configparser
raises the following error:

  configparser.InterpolationSyntaxError: '%' must be followed by '%' or
  '(', found: '%ip'

Using extended interpolation handler is a solution.